apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfsonar-web  
  namespace: perfsonar-platform
  labels:
    k8s-app: perfsonar-web
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: perfsonar-web
  template:
    metadata:
      labels:
        k8s-app: perfsonar-web
    spec:
      containers:
      - name: perfsonar-platform
        image: sslhep/perfsonar-platform-server:latest
        imagePullPolicy: Always
        command: ["python"]
        args: ["manage.py runserver 0.0.0.0:8000"]
        ports:
          - containerPort: 80
        # livenessProbe:
        #   httpGet:
        #     scheme: HTTP
        #     path: /healthz
        #     port: 80
        #   periodSeconds: 60
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 10
        volumeMounts:
        - name: frontend-conf-volume
          mountPath: "/usr/src/app/config/"
      volumes:
      - name: frontend-conf-volume
        secret:
          secretName: config-web
          items:
          - key: conf
            path: config.json      
